### ISSUE TITLE
how to serialize / deserialize?

### ISSUE THREAD

**Issue by coolaj86** [SalesforceEng/tough-cookie#24]
If I have a cookie jar such as `jar = new CookieJar()` how to I serialize that to JSON and then deserialize back to a CookeJar?

**Comment by GuillaumeLeclerc** [comment]
Same problem here :+1:

**Comment by GuillaumeLeclerc** [comment]
It seems `JSON.stringify` did the trick for me.

**Comment by inikulin** [comment]
Fixed via #42, published as v2.0.0
