### ISSUE TITLE
Do a 1.0.0 release and start following semver

### ISSUE THREAD

**Issue by domenic** [SalesforceEng/tough-cookie#31]
It would be great to be able to depend on getting feature updates and bugfixes in jsdom. Since the module is below version 1.0.0 right now we have no idea what will change in each release.

**Comment by stash-sfdc** [comment]
I think the API is pretty stable and philosophically I agree with you.

Are there any features or API you consider missing? (cc @inikulin)

**Comment by stash-sfdc** [comment]
https://github.com/SalesforceEng/tough-cookie/issues/9 is the only API-breaking change I'd like to make.

**Comment by stash-sfdc** [comment]
cc @lalitkapoor

**Comment by lalitkapoor** [comment]
I agree, I think this has been pretty stable for a while and happy to see it follow semver. I'd like to look at 2 bugs, but definitely not preventing a v1.0.0 release.

- https://github.com/SalesforceEng/tough-cookie/issues/16
- https://github.com/SalesforceEng/tough-cookie/issues/19 (request lib users have experienced this bug)

**Comment by inikulin** [comment]
@lalitkapoor #19 was fixed with #30.
@stash-sfdc The thing that bothers me most is the strict mode. If enabled it doesn't pass IETF's tests, therefore currently non-strict mode is stricter than "strict" mode. I suggest to get rid of "strict" mode. I can issue a PR if you are OK with it.

**Comment by stash-sfdc** [comment]
@inikulin :+1: if it actually isn't compliant, I'm OK with that. It will reduce a lot of complexity, both from the code and the API. If you don't have time, let me know and I'll take it on. :)

**Comment by inikulin** [comment]
@stash-sfdc I'll take care of it at Monday.

**Comment by stash-sfdc** [comment]
@inikulin ok, see #34

**Comment by stash-sfdc** [comment]
OK, just waiting for #16 now - there's a PR in the pipeline.

**Comment by stash-sfdc** [comment]
Er, wait, that doesn't need to be fixed for 1.0.x. I'll cut the release soon.

**Comment by stash-sfdc** [comment]
tough-cookie@1.0.0 published to NPM.
