### ISSUE TITLE
Remove Strict Mode

### ISSUE THREAD

**Issue by stash-sfdc** [SalesforceEng/tough-cookie#34]
Via @inikulin: 

> The thing that bothers me most is the strict mode. If enabled it doesn't pass IETF's tests, therefore currently non-strict mode is stricter than "strict" mode. So, I suggest to get rid of "strict" mode. I can issue a PR if you are OK with it.

In the interest of simplicity and compliance, we should remove this mode prior to 1.0.  This means an API breaking change, so let's maintain it on a "1.0-pre" branch in case we need to apply fixes to 0.x (currently 0.13)

**Comment by inikulin** [comment]
Forgot to switch remotes at first, sorry for that. Reverted and issued as pull request.
