### ISSUE TITLE
export MemoryCookieStore

### ISSUE THREAD

**Issue by apsavin** [SalesforceEng/tough-cookie#39]
Hi @stash!

Can we export MemoryCookieStore? So the users will be able to inherit from it.
I can send a PR, but the changes will be very small, as you understand.

**Comment by stash-sfdc** [comment]
Yes, it should be exported. I look forward to the PR :)

If the goal is serialization, the gotcha in serialization is picking a format for the dates so that round-trip they retain accuracy. JSON doesn't do that automatically.

**Comment by apsavin** [comment]
What about the same format that we use in Cookie#toString?

**Comment by inikulin** [comment]
It would be nice to move important business logic from the memory store to the base abstract class. So the only thing that should be implemented for the end-user store will be persistance strategy.

**Comment by stash-sfdc** [comment]
@inikulin that would be ideal. What I struggled with is a way to make the base class work with all the different types of indexing. There's at least three types: exact keys (e.g. redis, where you need to query on the permutation of domains and paths), radix indexing (bucketing after splitting on domain/path separators), and b-tree indexing (e.g. SQL prefix matching on path, suffix matching on domain).

**Comment by stash-sfdc** [comment]
@apsavin my mistake, I forgot this has already has been done. See `Cookie.fromJSON` which expects the dates to be in ISO format. Tests are in `test/cookie_to_json_test.js`

**Comment by stash-sfdc** [comment]
FWIW, I'm going to work on a simple JSON exporter today. Going to try make something that should work for any `Store` that wants to implement it.
