### ISSUE TITLE
Idea: new Store that bridges Mozilla cookies.sqlite format

### ISSUE THREAD

**Issue by stash-sfdc** [SalesforceEng/tough-cookie#41]
This definitely belongs in a separate NPM module. Working on a JSON serialization format made me wonder what Firefox was using. It seems to be an SQLite database file.

Overview: http://fileformats.archiveteam.org/wiki/Firefox_cookie_database

> The structure is seen in this SQL command embedded in the file:
> `CREATE TABLE moz_cookies (id INTEGER PRIMARY KEY, name TEXT, value TEXT, host TEXT, path TEXT,expiry INTEGER, lastAccessed INTEGER, isSecure INTEGER, isHttpOnly INTEGER, baseDomain TEXT, creationTime INTEGER)`

Official details: http://kb.mozillazine.org/Cookies

**Comment by stash-sfdc** [comment]
So, an async -- as opposed to `synchronous` like `MemoryCookieStore` -- would be really neat here since the data model mirrors almost exactly what tough-cookie expects.  Not surprising, really, but still neat. 

Wonder if Moz uses any kind of standard locking to control concurrency or if we have to tell folks "make a copy before modifying or you'll kill Firefox".

**Comment by lalitkapoor** [comment]
looks like this comes close in terms of db schema - https://github.com/JSBizon/db-cookie-store

**Comment by stash-sfdc** [comment]
OK great! if that one fits the bill then I think the right answer is to just link from the README. Leaving this issue open so that can be the "deliverable".

**Comment by JSBizon** [comment]
yeah this one https://github.com/JSBizon/db-cookie-store works for any db stores :)

**Comment by stash-sfdc** [comment]
OK! happy to leave it external.  Thanks @JSBizon !
