### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by tlianza** [SalesforceEng/tough-cookie#43]
I haven't spent a lot of time troubleshooting this, but I get a "undefined is not a function" error here:

tough-cookie/lib/cookie.js:320

The function I'm calling is Cookie.parse. And, the headers I'm passing in look like this:

``
[ 'sid=382aaefc-44b7-4a08-50e0-36d3f0343c4d; Path=/; Max-Age=360000',
  'uid=178; Path=/; Max-Age=360000' ]
``

**Comment by apsavin** [comment]
Cookie.parse expects string, not an array.
