### ISSUE TITLE
Include example of a cookie object in README

### ISSUE THREAD

**Issue by ablankenship10** [SalesforceEng/tough-cookie#44]
I'm trying to set a cookie to a cookie jar but it's not accepting anything I give it. Please add an example to the documentation.

    cookieJar.setCookie({key:"KEYNAME",value:"VALUE"},"http://myurl.com");

Does not work, returns undefined is not a function on str.trim(); When giving it the same as a JSON encoded string it returns Cookie failed to Parse. Whats wrong with this?

**Comment by apsavin** [comment]
it should be something like this:

```js
var cookie = new Cookie({key:"KEYNAME",value:"VALUE"/*, ...*/});
cookieJar.setCookie(cookie,"http://myurl.com");
```

**Comment by inikulin** [comment]
According to the [documentation] (https://github.com/SalesforceEng/tough-cookie#setcookiecookieorstring-currenturl-options-cberrcookie) `cookieJar.setCookie()` accepts `cookie string` or `cookie object`.  `cookie string` is a well-known term which means that cookie should be provided in the string form like in `Set-Cookie` header or in the `document.cookie` assignment. 
E.g.:
```js
"username=John Doe; expires=Thu, 18 Dec 2013 12:00:00 UTC; path=/"
```
