### ISSUE TITLE
JSON Obj to cookie

### ISSUE THREAD

**Issue by brunano21** [SalesforceEng/tough-cookie#50]
Hi,
 I have the following json obj representing a cookie, and I would like to set it into a `request` request, but I'm not able even looking at the doc and using Cookie.parse(obj).

    { 
        name: 'JSESSIONID',
        domain: 'mydomain',
        secure: false,
        path: '/',
        value: '0000AP8HRGxRDsY5sZLlnQU8d-U:-1',
        httpOnly: false 
    }
The following code produces:

    console.log(Cookie.fromJSON(cookies[i]));

    Cookie="=0000AP8HRGxRDsY5sZLlnQU8d-U:-1; Domain=mydomain; Path=/; hostOnly=?; aAge=?; cAge=0ms"

As you see, no name and httpOnly are set. Am I missing something?
Could you help please?
Thanks!

**Comment by stash-sfdc** [comment]
Use `key` instead of `name` and it should work.

```json
{ 
    key: 'JSESSIONID',
    domain: 'mydomain',
    secure: false,
    path: '/',
    value: '0000AP8HRGxRDsY5sZLlnQU8d-U:-1',
    httpOnly: false 
}
```
