### ISSUE TITLE
CookieJar.fromJSON is undefined

### ISSUE THREAD

**Issue by maraoz** [SalesforceEng/tough-cookie#57]
I think it's due to being defined before `deserializeSync` here:
https://github.com/SalesforceEng/tough-cookie/blob/master/lib/cookie.js#L1268

**Comment by stash-sfdc** [comment]
Oops! you're right.

**Comment by stash-sfdc** [comment]
Fix published in v2.2.1. Thanks for reporting @maraoz !

**Comment by maraoz** [comment]
Thanks!
