### ISSUE TITLE
permutePath is not returning original path

### ISSUE THREAD

**Issue by mediafreakch** [SalesforceEng/tough-cookie#61]
Assume i have the original path `/example/`. 
In this case `permutePath(originalPath)` would return: `['/example', '/' ]`.

I would expect it to return `['/example/', /example', '/']`. 

Without that I don't get a match for a cookie that stores `/example/`

**Comment by inikulin** [comment]
You need to use [pathMatch()](https://github.com/SalesforceEng/tough-cookie#pathmatchreqpathcookiepath) to perform actual matching according to RFC.
