### ISSUE TITLE
List all domains there are cookies for

### ISSUE THREAD

**Issue by MarkHerhold** [SalesforceEng/tough-cookie#62]
Hi,

How do I see all of the domains that there are cookies for? I'm sure this is a novice question and I apologize if I missed it in the documentation.

**Comment by inikulin** [comment]
Hi.

There is no finite list of domains that match the cookie. You can use `cookie.domain` property and test given domain using [domainMatch](https://github.com/SalesforceEng/tough-cookie#domainmatchstrdomstrcanonicalizetrue) function. The matching algorithm is described in details in [RFC 6265 S 5.1.3](https://tools.ietf.org/html/rfc6265#section-5.1.3).

**Comment by MarkHerhold** [comment]
I am actually asking for a complete list of all cookies in tough-cookie. I think this is actually close to what I am after: `Object.keys(cookieJar._jar.store.idx)`

**Comment by inikulin** [comment]
Oh, I see. Unfortunately we don't have this functionality out of the box. But `Object.keys(jar.store.idx)` is an acceptable workaround.
